[package]
name = "sysctl"
version = "0.1.0"
authors = ["Johannes Lundberg <johalun0@gmail.com>"]
description = "Simplified Rust interface to libc::sysctl"
keywords = ["sysctl", "freebsd"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/johalun/sysctl-rs"
documentation = "https://docs.rs/sysctl"

[dependencies]
libc = "0.2.22"
byteorder = "1.0.0"
errno = "0.2.3"

